name: SpawnerAdjuster
main: com.sadmean.mc.SpawnerAdjuster.SpawnerAdjuster
version: 1.9.2
author: Choelian
softdepend: [Vault]
commands:
    spawneradjusterreload:
       description: Reloads SpawnerAdjuster config file.
       usage: /spawneradjusterreload
       permission: SpawnerAdjuster.Commands.SAReload
       permission-message: You don't have proper permissions
       aliases: sareload
    spawneradjusterdebug:
       description: Runs a debug check.
       usage: /spawneradjusterdebug
       permission: SpawnerAdjuster.Commands.SADebug
       permission-message: You don't have proper permissions
    spawneradjusterspawndata:
       description: Collects and prints byte data of targeted spawner.
       usage: /spawneradjusterspawndata
       permission: SpawnerAdjuster.Commands.SASpawninfo
       permission-message: You don't have proper permissions
permissions:
    SpawnerAdjuster.*:
        description: Gives access to all SpawnerAdjuster functions
        children:
            SpawnerAdjuster.SetMobs.*: false
            SpawnerAdjuster.AlterMobs.*: false
            SpawnerAdjuster.BreakSpawners: false
            SpawnerAdjuster.DropSpawners: false
            SpawnerAdjuster.Commands.*: false
        default: false
    SpawnerAdjuster.Commands.*:
        description: Allows players to set all HOSTILE mob types on a monster spawner
        children:
            SpawnerAdjuster.Commands.SADebug: false
            SpawnerAdjuster.Commands.SAReload: false
            SpawnerAdjuster.Commands.SASpawndata: false
        default: false
    SpawnerAdjuster.SetMobs.*:
        description: Allows players to set all mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Neutral.*: false
            SpawnerAdjuster.SetMobs.Nether.*: false
            SpawnerAdjuster.SetMobs.Hostile.*: false
            SpawnerAdjuster.SetMobs.Utility.*: false
            SpawnerAdjuster.SetMobs.Boss.*: false
            SpawnerAdjuster.SetMobs.Unused.*: false
            SpawnerAdjuster.SetMobs.Entity.*: false
        default: false
    SpawnerAdjuster.AlterMobs.*:
        description: Allows players to change settings on all mob types on a monster spawner
        children:
            SpawnerAdjuster.AlterMobs.Creeper: false
        default: false
    SpawnerAdjuster.SetMobs.Neutral.*:
        description: Allows players to set all NEUTRAL mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Neutral.Pig: false
            SpawnerAdjuster.SetMobs.Neutral.Ocelot: false
            SpawnerAdjuster.SetMobs.Neutral.Wolf: false
            SpawnerAdjuster.SetMobs.Neutral.Enderman: false
            SpawnerAdjuster.SetMobs.Neutral.Sheep: false
            SpawnerAdjuster.SetMobs.Neutral.Cow: false
            SpawnerAdjuster.SetMobs.Neutral.Squid: false
            SpawnerAdjuster.SetMobs.Neutral.Mooshroom: false
            SpawnerAdjuster.SetMobs.Neutral.Villager: false
            SpawnerAdjuster.SetMobs.Neutral.Bat: false
        default: false
    SpawnerAdjuster.SetMobs.Hostile.*:
        description: Allows players to set all HOSTILE mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Hostile.Creeper: false
            SpawnerAdjuster.SetMobs.Hostile.Spider: false
            SpawnerAdjuster.SetMobs.Hostile.CaveSpider: false
            SpawnerAdjuster.SetMobs.Hostile.Skeleton: false
            SpawnerAdjuster.SetMobs.Hostile.Silverfish: false
            SpawnerAdjuster.SetMobs.Hostile.Slime: false
            SpawnerAdjuster.SetMobs.Hostile.Witch: false
            SpawnerAdjuster.SetMobs.Hostile.ZombieVillager: false
        default: false
    SpawnerAdjuster.SetMobs.Nether.*:
        description: Allows players to set all Nether mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Nether.Ghast: false
            SpawnerAdjuster.SetMobs.Nether.PigZombie: false
            SpawnerAdjuster.SetMobs.Nether.Blaze: false
            SpawnerAdjuster.SetMobs.Nether.MagmaCube: false
            SpawnerAdjuster.SetMobs.Nether.WitherSkeleton: false
        default: false
    SpawnerAdjuster.SetMobs.Unused.*:
        description: Allows players to set all Unsued mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Unused.Giant: false
        default: false
    SpawnerAdjuster.SetMobs.Utility.*:
        description: Allows players to set all Unsued mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Utility.SnowGolem: false
            SpawnerAdjuster.SetMobs.Utility.IronGolem: false
        default: false
    SpawnerAdjuster.SetMobs.Entity.*:
        description: Allows players to set non-creature entity types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Entity.Arrow: false
            SpawnerAdjuster.SetMobs.Entity.Boat: false
            SpawnerAdjuster.SetMobs.Entity.Fireball: false
            SpawnerAdjuster.SetMobs.Entity.Minecart: false
            SpawnerAdjuster.SetMobs.Entity.Egg: false
        default: false
    SpawnerAdjuster.SetMobs.Boss.*:
        description: Allows players to set all Unsued mob types on a monster spawner
        children:
            SpawnerAdjuster.SetMobs.Boss.EnderDragon: false
            SpawnerAdjuster.SetMobs.Boss.Wither: false
        default: false
    SpawnerAdjuster.Commands.SADebug:
        description: Allows players to run a debug check
        default: false
    SpawnerAdjuster.Commands.SAReload:
        description: Allows players to reload the config file
        default: false
    SpawnerAdjuster.Commands.SASpawndata:
        description: Allows a player to print byte data of spawner to console
        default: false
    SpawnerAdjuster.BreakSpawners:
        description: Allows players to break a monster spawner
        default: false
    SpawnerAdjuster.DropSpawners:
        description: Allows players to break a monster spawner
        default: false
    SpawnerAdjuster.SetMobs.Unused.Giant:
        description: Allows players to set a Monster Spawner to spawn Giants
        default: false
    SpawnerAdjuster.SetMobs.Nether.Ghast:
        description: Allows a player to set a Monster Spawner to spawn Ghasts
        default: false
    SpawnerAdjuster.SetMobs.Nether.PigZombie:
        description: Allows a player to set a Monster Spawner to spawn Pig Zombie Man
        default: false
    SpawnerAdjuster.SetMobs.Nether.WitherSkeleton:
        description: Allows a player to set a Monster Spawner to spawn Wither Skeleton
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Creeper:
        description: Allows a player to set a Monster Spawner to spawn Creepers
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Spider:
        description: Allows a player to set a Monster Spawner to spawn Spiders
        default: false
    SpawnerAdjuster.SetMobs.Hostile.CaveSpider:
        description: oh my god I hate typing all this permissions stuff
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Skeleton:
        description: Allows a player to set a Monster Spawner to spawn Skelebones
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Silverfish:
        description: Allows a player to set a Monster Spawner to spawn Silverfish
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Slime:
        description: Allows a player to set a Monster Spawner to spawn Slimes
        default: false
    SpawnerAdjuster.SetMobs.Hostile.Witch:
        description: Allows a player to set a Monster Spawner to spawn a Witch
        default: false
    SpawnerAdjuster.SetMobs.Hostile.ZombieVillager:
        description: Allows a player to set a Monster Spawner to spawn Zombie Villagers
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Cow:
        description: Allows a player to set a Monster Spawner to spawn Cows
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Sheep:
        description: Allows a player to set a Monster Spawner to spawn Sheep
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Wolf:
        description: Allows a player to set a Monster Spawner to spawn Wolf
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Enderman:
        description: Allows a player to set a Monster Spawner to spawn Endermen
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Pig:
        description: allows a Monster Spawner to set a player to spawn Pigs
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Squid:
        description: Allows a player to set a Monster Spawner to spawn Squid which is a bad idea
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Ocelot:
        description: Allows a player to set a Monster Spawner to spawn Ocelots
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Bat:
        description: Allows a player to set a Monster Spawner to spawn batss
        default: false
    SpawnerAdjuster.SetMobs.Boss.EnderDragon:
        description: Allows a player to set a Monster Spawner to spawn Ender Dragons
        default: false
    SpawnerAdjuster.SetMobs.Boss.Wither:
        description: Allows a player to set a Monster Spawner to spawn a Wither
        default: false
    SpawnerAdjuster.SetMobs.Utility.SnowGolem:
        description: Allows a player to set a Monster Spawner to spawn Snow Golems
        default: false
    SpawnerAdjuster.SetMobs.Utility.IronGolem:
        description: Allows a player to set a Monster Spawner to spawn Iron Golems
        default: false
    SpawnerAdjuster.SetMobs.Nether.Blaze:
        description: Allows a player to set a Monster Spawner to spawn Blazes
        default: false
    SpawnerAdjuster.SetMobs.Nether.MagmaCube:
        description: Allows a player to set a Monster Spawner to spawn a Magma Cubes. The hell
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Villager:
        description: Allows a player to set a Monster Spawner to spawn friends
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Mooshroom:
        description: Allows a player to set a Monster Spawner to spawn Mooshrooms
        default: false
    SpawnerAdjuster.SetMobs.Entity.Arrow:
        description: Allows a player to set a Monster Spawner to spawn arrows
        default: false
    SpawnerAdjuster.SetMobs.Entity.Boat:
        description: Allows a player to set a Monster Spawner to spawn boats
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Minecart:
        description: Allows a player to set a Monster Spawner to spawn Minecarts
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Fireball:
        description: Allows a player to set a Monster Spawner to spawn Fireballs
        default: false
    SpawnerAdjuster.SetMobs.Neutral.Egg:
        description: Allows a player to set a Monster Spawner to spawn Eggs
        default: false
    SpawnerAdjuster.AlterMobs.Creeper:
        description: Allows a player to set a Monster Spawner to spawn Charged Creepers
        default: false